# 网站配置
title: 小李家的菜单收藏
description: 一个精美的菜单收藏博客，展示每日精心准备的美食菜单
author: 小李
email: your-email@example.com
url: https://your-username.github.io/menu-blog

# 社交媒体
github_username: your-username
twitter_username: your-twitter

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 包含文件
include:
  - _pages

# 集合
collections:
  menus:
    output: true
    permalink: /:collection/:name/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "menus"
    values:
      layout: "menu"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
